version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5177:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=https://ktr-dev.take-off.kr
      - VITE_WS_URL=ws://ktr-dev.take-off.kr
    stdin_open: true
    tty: true
